version: '2'
services:
    kiosk-app:
        image: kiosk
        external_links:
            - kiosk-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/kiosk?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    kiosk-mysql:
        extends:
            file: mysql.yml
            service: kiosk-mysql
